config/routes.rb
Rails.application.routes.draw do
  root to: "orders#new"
  resources :orders, only: [:new]
  post '/order_billing', to: 'orders#billing'
  post '/order_shipping', to: 'orders#shipping'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: [:billing, :shipping, :confirmed]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
    @order = params[:order_id] ? Order.find(params[:order_id]) : Order.new
  end

  def billing
    if permitted_params[:order_id]
      @order = Order.find(permitted_params[:order_id])
      @order.update(billing_details: permitted_params[:billing_details])
    else
      @order = Order.new(permitted_params)
      @order.save
    end
  end

  def shipping
    @order = Order.find(permitted_params[:order_id])
    @order.shipping_address = permitted_params[:shipping_address]
    @order.save
  end

  private

  def permitted_params
    allowed = params.require(:order).permit(:billing_details, :status, :shipping_address, :order_id)
    allowed[:status] = allowed[:status].to_i
    allowed
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireForm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/billing.turbo_stream.erb
<%= turbo_stream.replace "billing" do %>
  <%= turbo_frame_tag 'billing' do %>
    <%= simple_form_for @order, url: order_shipping_path, method: :post, html: { data: { step: 'complete' } } do |f| %>
      <%= f.input :shipping_address %>
      <%= f.hidden_field :order_id, value: "#{@order.id}"  %>
      <%= f.submit :next %>
    <% end %>
  <% end %>
  <%= button_to "back", new_order_path(order_id: "#{@order.id}"), method: :get, data: { step: 'first'} %>
  <%#= link_to "back", new_order_path(order_id: "#{@order.id}"), method: :get, data: { step: 'first'} %>
<% end %>

app/views/orders/new.html.erb
<h1> A new form, a new journey </h1>
<div class="progress-bar">
  <div class="first" style="color: red"> 1 </div>
  <div class="second"> 2 </div>
  <div class="third"> 3 </div>
</div>

<%= turbo_frame_tag 'billing' do  %>
  <%= simple_form_for(@order, url: order_billing_path, method: :post,  html: { data: { step: :billing } } ) do |f| %>
    <%= f.input :billing_details %>
    <%= f.hidden_field :status, value: 1 %>
    <%=  f.hidden_field(:order_id, value: "#{@order.id}") unless @order.new_record? %>
    <%= f.submit :next %>
  <% end %>

<% end %>

app/views/orders/shipping.turbo_stream.erb
<%= turbo_stream.replace "billing" do %>
  <h4> Congrats! Your order is confirm </h4>
  <a href="#"> Continue Shopping! </a>
<% end %>